# Generated by Django 4.2.18 on 2025-02-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CategoryDescr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CourseDescription', models.CharField(max_length=100)),
                ('Abstract', models.TextField()),
                ('Bibliography', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('CycleId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CycleDescription', models.CharField(max_length=100)),
                ('CycleStartDate', models.DateField()),
                ('CycleEndDate', models.DateField()),
                ('VacationStartDate', models.DateField(blank=True, null=True)),
                ('VacationEndDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('BirthDate', models.DateField()),
                ('PhoneNo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestNo', models.IntegerField()),
                ('TestDate', models.DateField()),
                ('TestTime', models.TimeField()),
                ('Agenda', models.TextField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
            ],
            options={
                'unique_together': {('Course', 'Cycle', 'TestNo')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassNo', models.IntegerField()),
                ('ClassTitle', models.CharField(max_length=100)),
                ('ClassDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'unique_together': {('Course', 'Cycle', 'ClassNo')},
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
            options={
                'unique_together': {('Course', 'Cycle', 'Test', 'Student')},
            },
        ),
        migrations.CreateModel(
            name='TeachersPerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'unique_together': {('Course', 'Cycle', 'Teacher')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentDate', models.DateField()),
                ('Cancelled', models.BooleanField(default=False)),
                ('CancellationReason', models.CharField(blank=True, max_length=100, null=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('Course', 'Cycle', 'Student')},
            },
        ),
        migrations.CreateModel(
            name='CoursesPerCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseStartDate', models.DateField()),
                ('CourseEndDate', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
            ],
            options={
                'unique_together': {('Course', 'Cycle')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeArrive', models.TimeField(blank=True, null=True)),
                ('TimeLeave', models.TimeField(blank=True, null=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('Cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('Course', 'Cycle', 'Class', 'Student')},
            },
        ),
    ]
